version: '3'

services:
  shiodome:
    container_name: shiodome
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      MONGO_DB: "mongodb+srv://sakura:u3DtsEQ8xQnSnE@cluster0.zulrb8l.mongodb.net/?retryWrites=true&w=majority"